[package]
name = "bfrs"
version = "0.1.0"
authors = ["aiden01 <liangu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "3.8.1"
colored = "1.8.0"
cmdparser = "0.2.0"